# Generated by Django 3.0.5 on 2025-03-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='precautions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diseaserule',
            name='threshold_max',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='diseaserule',
            name='threshold_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseaserule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseaserule',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='unit',
            field=models.CharField(default='severity (0-10)', max_length=20),
        ),
    ]
